routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WallController;
use App\Http\Controllers\FilmController;
use App\Http\Controllers\AppartementController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\VisiteController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*//*
Route::get('/film', [FilmController::class,'index'])->middleware(['auth']);

Route::get('/filmshow/{id_film}', [FilmController::class,'filmshow'])->middleware(['auth']);

Route::get('/wall', [WallController::class,'index'])->middleware(['auth']);

Route::post('/postWall', [WallController::class,'save'])->middleware(['auth'])->name('postWall');

Route::get('/delete/{post_id}', [WallController::class,'delete'])->middleware(['auth'])->name('delete');

Route::get('/update/{post_id}', [WallController::class,'update'])->middleware(['auth'])->name('update');

Route::post('/update', [WallController::class,'store'])->middleware(['auth'])->name('store');
*/

Route::get('/visite/{id}', [VisiteController::class,'appartement_show'])->middleware(['auth']);

Route::get('/visite/{id}/rdv', [VisiteController::class,'rdv'])->middleware(['auth']);

Route::post('visite/rdv-enregistrer', [VisiteController::class,'rdv_enregistrer'])->middleware(['auth']);

/*Route::get('/test', function () {
    echo "test";
})->middleware(['auth']);*/

Route::get('/plop/{param}',function($param){
    echo '<b>plop : '.$param.'</b>';
});

Route::get('/hello/{username?}', function ($username = NULL) {
    return view('hello',['username' => $username]);
})->middleware(['auth']);

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/dashboard', [DashboardController::class,'index'])->middleware(['auth'])->name('dashboard');

Route::get('/visite', [VisiteController::class,'index'])->middleware(['auth'])->name('visite');

Route::get('/visite-corbeille', [VisiteController::class,'corbeille'])->middleware(['admin'])->name('appartementcorbeille');

Route::get('/appartement/corbeille/{id}', [AppartementController::class,'corbeille'])->middleware(['admin'])->name('corbeille');

Route::get('/visite-restaure/{id}', [VisiteController::class,'restaure'])->middleware(['admin'])->name('retirercorbeille');

Route::get('/visite-delete/{id}', [AppartementController::class,'delete'])->middleware(['admin'])->name('deleteappartement');

Route::get('/mesvisite', [VisiteController::class,'mesvisite'])->middleware(['auth'])->name('mesvisite');

Route::get('/mesdemande', [AppartementController::class,'mesdemande'])->middleware(['auth'])->name('mesdemande');

// Route::get('/appartement',[AppartementController::class,'index'])->middleware(['auth'])->name('appartement');

Route::get('/appartement/demande/{id}',[AppartementController::class,'demande'])->middleware(['auth'])->name('demande');

Route::get('/addappartement', [AppartementController::class,'create'])->middleware(['admin'])->name('addappartement');

Route::post('/appartement/register', [AppartementController::class,'addappartement'])->middleware(['admin'])->name('addappartement-succes');

Route::get('/appartement-edit/{id}', [AppartementController::class,'edit'])->middleware(['admin'])->name('appartementedit');

Route::post('/appartement-edit/single', [AppartementController::class,'update'])->middleware(['admin'])->name('appartementeditsuccess');

Route::get('/admin/validation-visite', [VisiteController::class,'validation_liste'])->middleware(['admin'])->name('validation');

Route::get('/admin/validation-visite/{id}', [VisiteController::class,'validation'])->middleware(['admin'])->name('valider');

Route::get('/admin/validation-biens', [AppartementController::class,'validation_liste'])->middleware(['admin'])->name('validation_bien');

Route::get('/admin/validation-bien/{id}', [AppartementController::class,'validation'])->middleware(['admin'])->name('valider_bien');


require __DIR__.'/auth.php';
 

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/appartement_corbeille.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            welcome on the appartement !
        </h2>
    </x-slot>
 
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <!-- <th scope="col">ID</th> -->
                                <th scope="col">Réference</th>
                                <th scope="col">Type</th>
                                <th scope ="col" > nb_piece</th>
                                <th scope ="col">Prix</th>
                                <th scope ="col">Surface</th>
                                <th scope ="col">Status</th>
                                <th scope ="col">Date publication</th>
                                <th scope ="col" >Restaure</th>
                                <th scope ="col" >Supprimer Définitivement</th>

                            </tr>
                        </thead>    
                        @foreach ($appartements as $appartement)
                        <tr>
                            <!-- <td>    {{ $appartement->id }} </td> -->
                            <td>    {{ $appartement->id }}</td>
                            <td>    {{ $appartement->type }}</td>
                            <td>    T{{ $appartement->nb_piece }}</td>
                            <td>    {{ $appartement->prix }}</td>
                            <td>    {{ $appartement->surface }}</td>
                            <td>    {{ $appartement->status }}</td>
                            <td>    {{ $appartement->date_publication }}</td>
                            <td><a href="/visite-restaure/{{ $appartement->id }}">Restaure</a>
                            <td><a href="/visite-delete/{{ $appartement->id }}">Delete</a>
                        </tr>
                        @endforeach
                    </table>
   
                    <button><a href="/visite">Retourner</a></button>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/demande_envoyer.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            RDV-enregistrer
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    
                    <h1>Demande 
                        @if ($appartement->status == "louer")
                            location
                        @else
                            d'achat
                        @endif
                        a été envoyer à notre centre de validation
                    </h1>
                    <div style = "border:solid green;margin:5px;border-radius:20px;padding:20px;">
                        <h2>Merci pour votre confiance</h2>
                        <p>Votre demande sera valider dans les plus brefs delai<p>
                        <p>Reference lot : {{ $appartement->id }}</p>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/film.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            welcome on the wall ! 
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <ul>
                    @foreach ($films as $film)
                        <li>{{ $film->titre }}
                        <a href="/filmshow/{{ $film->id_film }}">(show)</a>
                        </li>
                    @endforeach
                    </ul>
                    {{ $films->links() }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/hello.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Hello 
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    @if(!empty($username))
                        {{ $username }}
                    @endif
                    Bienvenue sur notre première vue ! 
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/rdv-enregistrer.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            RDV-enregistrer
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <h1>Rdv enregistrer</h1>
                    <p>Un mail de confirmation vous serez envoyé dans les minutes qui suivent</p>
                    <p>Votre date de RDV est le {{ $date }} . </p>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/rdv-visite.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Prendre Viste
        </h2>
    </x-slot>


    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <h1>Formulaire pour prendre une visite </h1>
                    <div class="form-rdv">
                        <form action="/visite/rdv-enregistrer" method="post">
                            @csrf
                            <label>Numéro de lot</label>
                            <input type="text" value = 'Lot : {{ $id }}' disabled="disabled"><br>
                            <input type="number" value = '{{ $id }}' name="id_appartement" hidden>
                            <label>Choisir une date de visite</label>
                            <input type ="date" name="date_rdv" id="date-rdv" required>
                        <button type="submit">Envoyer</button>
                    </div>    
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>
    var today = new Date();
    var dd = String(today.getDate()).padStart(2, '0');
    var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
    var yyyy = today.getFullYear();
    today = yyyy+'-'+mm+'-'+dd;
    document.getElementById("date-rdv").min = today;
</script>
</x-app-layout>

resources/views/single-appartement-edit-success.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Hello 
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                     <h1> Appartement N° {{ $id }} a été modifié  </h1>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/single-appartement-edit.blade.php
<x-app-layout>

    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            welcome FilmShow Page ! 
        </h2>
    </x-slot>
    
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="centerboridehi">
                        <h1 style="text-align:center;margin-bottom:40px;">
                        @if($appartement->type =="appartement")
                            Appartement
                        @else
                            Maison
                        @endif
                        Lot N° {{ $appartement->id }} </h1>

                        <form action="/appartement-edit/single" method="post">
                          
                            @csrf
                            <label>ID Appartement</label>
                            <select name ="id">
                                <option value=<?php echo $appartement->id; ?>><?php echo $appartement->id; ?></option>
                            </select>
                           
                            <label>Type</label>
                            <select name="type">
                                <option value="appartement">Appartement</option>
                                <option value="maison" <?php if($appartement->type == "maison"){ echo "Selected" ; } ?> >Maison</option>
                            </select>
                            <label>Nombre de pièce</label>
                            <select name="nb_piece">
                            <?php for($i=1 ; $i<=150 ; $i++){
                                    if ($appartement->nb_piece == $i){
                                        echo "<option value=$i selected>$i</option>";
                                    }
                                    else{ 
                                    echo "<option value=$i>$i</option>";}
                                } ?>
                            </select>
                            <label>Etage</label>
                            <select name="etage">
                                <?php for($i=1 ; $i<=150 ; $i++){
                                    if ($appartement->etage == $i){
                                        echo "<option value=$i selected>$i</option>";
                                    }
                                    else{ 
                                    echo "<option value=$i>$i</option>";}
                                } ?>
                            <select>
                            <label>Status
                            <select name="status">
                                <option value="vente">Vente</option>
                                <option value="location" <?php if($appartement->status == "location"){ echo "Selected" ; } ?>>location</option>
                            </select></label>
                            <label>Prix</label>
                            <input type="number" max="1000000000" name="prix"  placeholder=<?php echo $appartement->prix; ?>>
                            <label>Surface m²</label>
                            <input type="number" max="100000" name="surface"  placeholder=<?php echo $appartement->surface ;?>> 
                            <label>Adresse</label>
                            <input type="text" name="adresse"  placeholder=<?php echo $appartement->adresse ; ?>>
                            <label>localisation (Facultatif)</label>
                            <input type="text" name="localisation" placeholder=<?php echo $appartement->localisation; ?>>

                            <label>Images</label>
                            <input type="file" name="images" accept="image/*" multiple>

                            <label>Description
                            <input type="text" name="description"  placeholder=<?php echo $appartement->description; ?>></label>
                            <input type="submit">

                   
                        </form>
                    </div>
                </div>
                    
            </div>
            
        </div>
    </div>
   
</x-app-layout>

resources/views/single-appartement.blade.php
<x-app-layout>

    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            welcome FilmShow Page ! 
        </h2>
    </x-slot>
    
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="centerboridehi">
                        <h1 style="text-align:center;margin-bottom:40px;">
                        @if($appartement->type =="appartement")
                            Appartement
                        @else
                            Maison
                        @endif
                        Lot N° {{ $appartement->id }} </h1>
                    </div>
                    @if (!empty($images[0]))
                        <div class="slideshow-container">
                            @foreach ($images as $image)
                                <div class="mySlides fade">
                                <img src="{{ asset($image->image_url) }}" alt="job image" style="width:100%; height:500px;">
                                </div>
                            @endforeach
                            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                            <a class="next" onclick="plusSlides(1)">&#10095;</a>
                        </div>
                   
                        <br>

                        <!-- The dots/circles -->
                        <div style="text-align:center">
                        @foreach ($images as $key => $image)
                            <span class="dot" onclick="currentSlide({{ $loop->iteration }})"></span>
                        @endforeach
                    @endif    
                    <div class = "tableau-info">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <!-- <th scope="col">ID</th> -->
                                    <th scope="col">Type</th>
                                    <th scope ="col">Pièce</th>
                                    <th scope ="col">Prix</th>
                                    <th scope ="col">Surface</th>
                                    <th scope ="col">Date publication</th>
                                </tr>
                            </thead>
                            <tr>
                                <td>{{ $appartement->type }}</td>
                                <td>T{{ $appartement->nb_piece }}</td>
                                <td>{{ $appartement->prix }}€</td>
                                <td>{{ $appartement->surface }}m²</td>
                                <td>{{ $appartement->date_publication }}</td>
                            </tr>
                        </table>


                    </div>
                    <center>
                        <h1 style="text-align:center;margin-bottom:20px;"> Description </h1>
                        <p> {{ $appartement->description }}</p>
                        <div>
                            <h1 style="text-align:center;margin-bottom:20px;">Localisation</h1>
                            <p> {{ ($appartement->adresse )}} <p>

                            <iframe src="{{ asset($appartement->localisation) }}" width="600" height="450" style="border:0;margin:auto;" allowfullscreen="" loading="lazy"></iframe>
                
                        </div>
                        <button type="button" class="bouton-visite" name="bouton-visite"><a href="/visite/{{ $appartement->id}}/rdv">Choisir Date de visite</a></button>
                    </center>
                </div>
                    
            </div>
            
        </div>
    </div>
    <script type="text/javascript" src="{{ asset('js/slider.js') }}"></script>
</x-app-layout>

resources/views/update.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            welcome on the wall Update ! 
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    {!! Form::open(['route' => 'store']) !!}
                        {!! Form::text('content', $post->content) !!}
                        {!! Form::hidden('post_id',$post->id) !!}
                        {!! Form::submit('Update !!!! ') !!}
                    {!! Form::close() !!}

                    
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/validation_bien.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            welcome on the appartement !
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <!-- <th scope="col">ID</th> -->
                                <th scope ="col">Reference</th>
                                <th scope ="col">Type</th>
                                <th scope ="col">Adresse</th>
                                <th scope ="col">Demandeur</th>
                                <th scope ="col">Demande</th>
                                <th scope ="col">Confirmation</th>
                            </tr>
                        </thead>    
                        @foreach ($appartements as $appartement)
                        <tr>
                            <th scope ="col"> {{ $appartement->id }}</th>
                            <th scope ="col">{{ $appartement->type }}</th>
                            <th scope ="col">{{ $appartement->adresse }}</th>
                            <th scope ="col">{{ $appartement->name }}</th>
                            <th scope ="col">
                            @if ($appartement->status == "louer")
                                Location</th>
                                <th scope ="col" style="color:green;"><a href="/admin/validation-bien/{{ $appartement->id }}">Confirmer Location </a></th>
                                
                            @else
                                Achat Total</th>
                                <th scope ="col" style="color:green;"><a href="/admin/validation-bien/{{ $appartement->id }}">Confirmer Vente </a></th>
                            @endif
                            
                        </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/validation_visite.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            welcome on the appartement !
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <!-- <th scope="col">ID</th> -->
                                <th scope ="col">Reference Visite</th>
                                <th scope ="col">Lot Appartement</th>
                                <th scope ="col">Adresse</th>
                                <th scope ="col">Date de visite</th>
                                <th scope ="col">Visiteur</th>
                                <th scope ="col">Status</th>
                                <th scope ="col">Confirmation</th>
                            </tr>
                        </thead>    
                        @foreach ($lesvisites as $levisite)
                        <tr>
                            <th scope ="col"> {{ $levisite->id }}</th>
                            <th scope ="col">{{ $levisite->id_appartement }}</th>
                            <th scope ="col">{{ $levisite->adresse }}</th>
                            <th scope ="col">{{ $levisite->date_visite }}</th>
                            <th scope ="col">{{ $levisite->name }}</th>
                            @if ($levisite->isValide == 0)
                                <th scope ="col" style="color:red;">En Attente de validation</th>
                            @else 
                                <th scope ="col" style="color:green;">Validée</th>
                            @endif
                            <th scope ="col" style="color:green;"><a href="/admin/validation-visite/{{ $levisite->id }}">Confirmer RDV</a></th>
                        </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/visite.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Visite') }}
        </h2>
    </x-slot>
</x-app-layout
>

resources/views/wall.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            welcome on the wall ! 
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    {!! Form::open(['route' => 'postWall']) !!}
                        {!! Form::text('content') !!}
                        {!! Form::submit('Post on the Wall Click Me!') !!}
                    {!! Form::close() !!}

                    contenu de wall : <br> 
                    <ul>
                    @foreach ($posts as $post)
                        <li>{{ $post->content }}
                            <a href="/delete/{{ $post->id }}">(delete)</a>
                            <a href="/update/{{ $post->id }}">(update)</a>
                        </li>
                    @endforeach
                    </ul>
                    {{ $posts->links() }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>